config/routes.rb
Rails.application.routes.draw do
  devise_for :employees
  root "departments#index"
  resources :employees do
    resources :feedbacks
  end
  resources :departments do
    resources :feedbacks
  end
  resources :feedbacks
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/department.rb
class Department < ApplicationRecord
  has_one_attached :cover
  has_many :employees, dependent: :destroy
  has_many :receive_feedbacks, class_name: "Feedback", as: :feedbackable, dependent: :destroy
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :department, counter_cache: true
  belongs_to :manager, class_name: 'Employee', optional: true
  has_many :reports, class_name: "Employee", foreign_key: "manager_id", dependent: :destroy, inverse_of: "manager"
  has_one_attached :avatar
  has_many :feedbacks, dependent: :destroy
  has_many :receive_feedbacks, class_name: "Feedback", as: :feedbackable, dependent: :destroy

  enum role: { admin: 0, regular: 1}
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :employee
  belongs_to :feedbackable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_employee!
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: %i[ show edit update destroy ]

  # GET /departments or /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1 or /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments or /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to department_url(@department), notice: "Department was successfully created." }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1 or /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to department_url(@department), notice: "Department was successfully updated." }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1 or /departments/1.json
  def destroy
    @department.destroy

    respond_to do |format|
      format.html { redirect_to departments_url, notice: "Department was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def department_params
      params.require(:department).permit(:name, :description, :cover)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)
    unless @employee.avatar.attached?
      @employee.avatar.attach(io: File.open("app/assets/images/default.png"), filename: "default.png")
    end

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee.department, notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:name, :nationality, :email, :position, :department_id, :birth_date, :manager_id, :role, :avatar, :password)
    end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: %i[ show edit update destroy ]

  # GET /feedbacks or /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1 or /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks or /feedbacks.json
  def create
    if params[:employee_id]
      feedbackable = Employee.find(params[:employee_id])
    elsif params[:department_id]
      feedbackable = Department.find(params[:department_id])
    end
    @feedback = Feedback.new(feedback_params)
    @feedback.feedbackable = feedbackable

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback.feedbackable, notice: "Feedback was successfully created." }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1 or /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to feedback_url(@feedback), notice: "Feedback was successfully updated." }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1 or /feedbacks/1.json
  def destroy
    @feedback.destroy

    respond_to do |format|
      format.html { redirect_to @feedback.feedbackable, notice: "Feedback was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def feedback_params
      params.require(:feedback).permit(:body, :employee_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/departments/_department.html.erb
<div id="<%= dom_id department %>" class="department--card">
    <% if department.cover.attached? %>
        <%= image_tag(department.cover, alt: "Cover Departament")%>
    <% end %>
  <div class="department--card__title">
    <p class="department--card__name">
      <strong><%= link_to department.name, department %></strong>
    </p>
    <p class="department--card__count">
      <%= department.employees_count %> employees
    </p>
  </div>
  <div class="department--card__link">
    <%= link_to image_tag("edit.png", alt: "Edit"), edit_department_path(department) %>
    <%= link_to image_tag("trash.png", alt: "Trash"), department, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  </div>
</div>

app/views/departments/_form.html.erb
<%= form_with(model: department) do |form| %>
  <% if department.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
        <% department.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block", class: "label--department" %>
    <%= form.text_field :name, class: "input input--department", placeholder: "Secret planning" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block", class: "label--department" %>
    <%= form.text_area :description, class: "input input--department", placeholder: "This is the best department yet..." %>
  </div>

  <div>
    <%= form.label :cover, style: "display: block", class: "label--department"%>
    <%= form.file_field :cover, class: "input" %>
  </div>

  <div>
    <%= form.submit class: "input buttom--department__create" %>
  </div>
  <%= link_to "Back", departments_path, class: "input buttom--department__back"%>
<% end %>

app/views/departments/edit.html.erb
<h1 class="title">Edit Department</h1>
<div class="new--department">
<%= render "form", department: @department %>
</div>

app/views/departments/index.html.erb
<h1 class="title">Departments</h1>

<div class="button--department">
  <%= link_to "NEW DEPARTMENT", new_department_path %>
</div>
<div id="departments">
  <% @departments.each do |department| %>
    <%= render department %>
  <% end %>
</div>

app/views/departments/new.html.erb
<h1 class="title">New Department</h1>

<div class="new--department">
  <%= render "form", department: @department %>
</div>

app/views/departments/show.html.erb
<div>
    <p class="title">
      <%= @department.name %>
    </p>
    
</div>
<div class="new--department">
  <p class="description--department">
    <%= @department.description %>
  </p>

  <%= link_to "New Employee", new_employee_path, class: "buttom--employee__create"%>

  <div class="department--information">
    <h4>Employees</h4>
    <% @department.employees.each do |employee| %>
      <%= render "employees/employee_card" , employee: employee%>
    <% end %>
  </div>
  <div class="department--information">
    <h4>Feedback</h4>
    
    <%= render "feedbacks/form", {feedback: Feedback.new, feedbackable: @department } %>
  
    <% @department.receive_feedbacks.each do |feedback| %>
    <div class="feedback--card">
      <p class="feedback--name">By <%= feedback.employee.name %></p>
      <p class="feedback--body"><%= feedback.body %></p>
      <div class="feedback--link">
        <p class="feedback--created"><%= feedback.created_at %></p>
        <%= link_to image_tag("trash.png", alt: "Trash"), feedback, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
      </div>
    </div>
    <% end %>
    <%= link_to "Back", departments_path, class: "input buttom--department__back"%>
  </div>
</div>

app/views/employees/_employee.html.erb
<div id="<%= dom_id employee %>">
<div class="new--department">
  <div class="avatar--imagen">
    <% if employee.avatar.attached? %>
      <%= image_tag employee.avatar%>
    <% end %>
  </div>
  <p class="employee--name__details">
    <%= employee.name %>
  </p>
  <p class="employee--position__details">
    <%= employee.position %>
  </p>
    <p class="employee--deptname__details">
    <%= employee.department.name %>
  </p>
  <p class="employee--nationality__details">
    <%= employee.nationality %>
  </p>
  <p class="employee--years">
    <% if employee.birth_date %>
      <%= ((Time.zone.now - employee.birth_date.to_time) / 1.year.seconds).floor  %>
      years
    <% else %>
      No birth date
    <% end %>
  </p>

<div class="employee--link">
  <%= link_to image_tag("edit.png", alt: "Edit"), edit_employee_path(employee) %>
  <%= link_to image_tag("trash.png", alt: "Trash"), employee, method: :delete %>
</div>
  <p>
   <strong>Manager</strong>
   <% if employee.manager_id %>
     <%= render "employee_card", employee: employee %>
   <% else %>
      No Manager
    <% end %>
  </p>
  <p>
   <strong>Reports</strong>
    <% employee.reports.each do |report| %>
      <%= render "employee_card", employee: report %>
    <% end %>
    <%= "No reports" if employee.reports.empty? %>
  </p>

  <h3>Feedback</h3>
  
  <%= render "feedbacks/form", {feedback: Feedback.new, feedbackable: employee } %>
  <% employee.receive_feedbacks.each do |feedback| %>
  <div class="feedback--card">
    <p class="feedback--name">By <%= feedback.employee.name %></p>
    <p class="feedback--body"><%= feedback.body %></p>
    <div class="feedback--link">
        <p class="feedback--created"><%= feedback.created_at %></p>
        <%= link_to image_tag("trash.png", alt: "Trash"), feedback, method: :delete %>
    </div>
  </div>
  <% end %>
  <%= link_to "Back", departments_path , class: "input buttom--department__back"%>
</div>
</div>

app/views/employees/_employee_card.html.erb
<div class="employee--card">
  <div>
    <div class="employee--details">
      <div class="employee--avatar">
        <%if employee.avatar.attached? %>
          <%= image_tag(employee.avatar, alt:"Employee avatar")%>
        <% end %>
      </div>
      <div class="employee--information">
        <p class="employee--name"><%= link_to employee.name, employee %></p>
        <p class="employee--position"><%= employee.position %></p>
      </div>
    </div>
  </div>
  <div class="employee--card__link">
      <%= link_to image_tag("edit.png", alt: "Edit"), edit_employee_path(employee) %>
      <%= link_to image_tag("trash.png", alt: "Trash"), employee_path(employee), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
  </div>
</div>

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block", class: "label--department" %>
    <%= form.text_field :name, class: "input input--department", placeholder: "John Doe" %>
  </div>

  <div>
    <%= form.label :nationality, style: "display: block", class: "label--department" %>
    <%= form.text_field :nationality, class: "input input--department", placeholder: "Peru" %>
  </div>

  <div>
    <%= form.label :email, style: "display: block", class: "label--department" %>
    <%= form.text_field :email, class: "input input--department", placeholder: "example@mail.com" %>
  </div>

  <div>
    <%= form.label :position, style: "display: block", class: "label--department" %>
    <%= form.text_field :position, class: "input input--department", placeholder: "eternal apprentice" %>
  </div>

  <div>
    <%= form.label :birth_date, style: "display: block", class: "label--department" %>
    <%= form.date_field :birth_date, class: "input input--department" %>
  </div>

  <div>
    <%= form.label :department_id, style: "display: block", class: "label--department" %>
    <%= form.collection_select :department_id, Department.order(:name), :id, :name, {}, class: "input input--department"  %>
  </div>

  <div>
    <%= form.label :manager_id, style: "display: block", class: "label--department" %>
    <%= form.collection_select :manager_id, employee.id ? Employee.where("id != ?", employee.id) : Employee.order(:name), :id, :name, {}, include_blank: "Select manager", class: "input input--department" %>
  </div>

  <div>
    <%= form.label :avatar, style: "display: block", class: "label--department" %>
    <%= form.file_field :avatar, class: "input" %>
  </div>

  <div>
    <%= form.submit class: "input buttom--department__create"%>
  </div>
  <%= link_to "Back", departments_path, class: "input buttom--department__back"%>
<% end %>

app/views/employees/edit.html.erb
<h1 class="title">Editing employee</h1>

<div class="new--department">
  <%= render "form", employee: @employee %>
</div>

app/views/employees/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Employees</h1>

<div id="employees">
  <% @employees.each do |employee| %>
    <%= render employee %>
    <p>
      <%= link_to "Show this employee", employee %>
    </p>
  <% end %>
</div>

<%= link_to "New employee", new_employee_path %>

app/views/employees/new.html.erb
<h1 class="title">New Employee</h1>

<div class="new--department">
  <%= render "form", employee: @employee %>
</div>

app/views/employees/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @employee %>

app/views/feedbacks/_feedback.html.erb
<div id="<%= dom_id feedback %>">
  <p>
    <strong>Body:</strong>
    <%= feedback.body %>
  </p>

  <p>
    <strong>Employee:</strong>
    <%= feedback.employee_id %>
  </p>

  <p>
    <strong>Feedbackable ID:</strong>
    <%= feedback.feedbackable_id %>
  </p>

  <p>
    <strong>Feedbackable Type:</strong>
    <%= feedback.feedbackable_type %>
  </p>

</div>

app/views/feedbacks/_form.html.erb
<%= form_with(model: [feedbackable, feedback]) do |form| %>
  <div>
    <%= form.text_area :body, class: "input input--department", placeholder: "Remember to use"%>
  </div>

  <div>
    <%= form.collection_select :employee_id, Employee.order(:name), :id, :name %>
  </div>
  
  <div>
    <%= form.submit value: "Send Feedback", class: "input buttom--department__create"%>
  </div>

  <% if feedback.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
        <% feedback.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing feedback</h1>

<%= render "form", feedback: @feedback %>

<br>

<div>
  <%= link_to "Show this feedback", @feedback %> |
  <%= link_to "Back to feedbacks", feedbacks_path %>
</div>

app/views/feedbacks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Feedbacks</h1>

<div id="feedbacks">
  <% @feedbacks.each do |feedback| %>
    <%= render feedback %>
    <p>
      <%= link_to "Show this feedback", feedback %>
    </p>
  <% end %>
</div>

<%= link_to "New feedback", new_feedback_path %>

app/views/feedbacks/new.html.erb
<h1>New feedback</h1>

<%= render "form", feedback: @feedback %>

<br>

<div>
  <%= link_to "Back to feedbacks", feedbacks_path %>
</div>

app/views/feedbacks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @feedback %>

<div>
  <%= link_to "Edit this feedback", edit_feedback_path(@feedback) %> |
  <%= link_to "Back to feedbacks", feedbacks_path %>

  <%= button_to "Destroy this feedback", @feedback, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Offix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="main">
    <header class="header">
      <div class="logo--header">
        <%= link_to root_path do %>
          <%= image_tag("logo.svg", alt:"Logo")%>
        <% end %>
      </div>
      <%if employee_signed_in? %>
      <div class="signed--header">
        <%= link_to "Sign out", destroy_employee_session_path, data: { "turbo_method": :delete}%>
      </div>
      <%end%>
      <div class="menu--header">
        <%= image_tag("menu.png", alt:"Menu") %>
      </div>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <footer class="footer">
      <p>C7 - 2022</p>
    </footer>
    </div>
  </body>
</html>